# 80表述注册到zookeeper的消费者端口号
server:
  port: 8080

# 服务别名---zookeeper注册中心名称
spring:
  application:
    name: cloud-provider-order
  cloud:
    # zookeeper的地址
    zookeeper:
      connect-string: 127.0.0.1:2181
